### ISSUE TITLE
esp32-cam fails when building

### ISSUE THREAD

**Issue by elo1957** [bkeevil/esp32-cam#33]
I'm using esp-idf ver 4.3 and get this 

r_support\CMakeFiles\__idf_bootloader_support.dir\src\bootloader_common.c.obj.d -o esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_common.c.obj   -c C:/Users/osc/Desktop/esp-idf/components/bootloader_support/src/bootloader_common.c
In file included from C:/Users/osc/Desktop/esp-idf/components/soc/include/soc/rtc_periph.h:17,
                 from C:/Users/osc/Desktop/esp-idf/components/soc/esp32/include/soc/rtc.h:20,
                 from C:/Users/osc/Desktop/esp-idf/components/bootloader_support/src/bootloader_common.c:37:
C:/Users/osc/Desktop/esp-idf/components/soc/include/soc/rtc_io_periph.h:111:44: error: 'GPIO_PIN_COUNT' undeclared here (not in a function); did you mean 'SOC_GPIO_PIN_COUNT'?    
 extern const rtc_gpio_desc_t rtc_gpio_desc[GPIO_PIN_COUNT];
                                            ^~~~~~~~~~~~~~
                                            SOC_GPIO_PIN_COUNT
_ found that a header file "esp_intr_alloc.h" is missing in ver 4.3  - i manually found it in and SDK arduino esp version

**Comment by bkeevil** [comment]
You need to either install version 4.0 of the ESP-IDF, which this project is compatible with, or update the source code for version 4.3
