### ISSUE TITLE
Header fields are too long for server to interpret

### ISSUE THREAD

**Issue by Kasperdelasopa** [bkeevil/esp32-cam#39]
I'm barely able to connect to the esp32-cam

in 90% there is the error "Header fields are too long for server to interpret". The error is also visible on the Serial port.

Is there a configuration i might missed?

Best regards

**Comment by bkeevil** [comment]
I have not heard of that error before. Can you see if you get this error with the version of the code base prior to the last pull request that was merged:

 `git checkout 40299202dc5105646c6cb2937a2e8610dd6f75a2`

**Comment by Kasperdelasopa** [comment]
I tried that version --> Same result

BUT: I found a configuration for the HTTP header length in the which seems to do the job. 

Know it seems i have a hardware problem which is not part of this issue.

--> THX
