### ISSUE TITLE
Soft AP starts but no connection to httpd

### ISSUE THREAD

**Issue by g8ecj** [bkeevil/esp32-cam#8]
I tried using an unknown SSID for the WIFI connection to force the soft AP to start. It appears that it does OK, I can connect to it and I can ping the IP address but no httpd access.

**Comment by g8ecj** [comment]
Duh. It helps if you read the monitor output correctly! The IP address (192.168.4.2) I could ping was the one allocated to the station. Pinging that of course works (its localhost!!). The default AP IP that I'd set of 192.168.4.1 works fine.
Sorry for the noise

**Comment by bkeevil** [comment]
Thanks for your work testing it :-)
